=== akos-asztalos443/JTUBQHWebXML/JTUBQH_1014/JTUBQH_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="JTUBQH_Vendeglatas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Etterem" type="etteremTipus" maxOccurs="unbounded"/>
                <xs:element name="Foszakacs" type="foszakacsTipus" maxOccurs="unbounded"/>
                <xs:element name="Szakacs" type="szakacsTipus" maxOccurs="unbounded"/>
                <xs:element name="Gyakornok" type="gyakornokTipus" maxOccurs="unbounded"/>
                <xs:element name="Vendeg" type="vendegTipus" maxOccurs="unbounded"/>
                <xs:element name="rendeles" type="rendelesTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        
        <xs:key name="etterem_kulcs">
            <xs:selector xpath="Etterem"/>
            <xs:field xpath="@EKod"/>
        </xs:key>

        <xs:key name="foszakacs_kulcs">
            <xs:selector xpath="Foszakacs"/>
            <xs:field xpath="@FKod"/>
        </xs:key>

        <xs:key name="szakacs_kulcs">
            <xs:selector xpath="Szakacs"/>
            <xs:field xpath="@SzKod"/>
        </xs:key>

        <xs:key name="gyakornok_kulcs">
            <xs:selector xpath="Gyakornok"/>
            <xs:field xpath="@GyKod"/>
        </xs:key>

        <xs:key name="vendeg_kulcs">
            <xs:selector xpath="Vendeg"/>
            <xs:field xpath="@VKod"/>
        </xs:key>

        
        <xs:keyref name="etterem_idegen_kulcs" refer="etterem_kulcs">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@e_v_e"/>
        </xs:keyref>

        <xs:keyref name="vendeg_idegen_kulcs" refer="vendeg_kulcs">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@e_v_v"/>
        </xs:keyref>

        <xs:keyref name="etterem_foszakacs_idegen_kulcs" refer="etterem_kulcs">
            <xs:selector xpath="Foszakacs"/>
            <xs:field xpath="@E_F"/>
        </xs:keyref>

        <xs:keyref name="etterem_szakacs_idegen_kulcs" refer="etterem_kulcs">
            <xs:selector xpath="Szakacs"/>
            <xs:field xpath="@E_SZ"/>
        </xs:keyref>

        <xs:keyref name="etterem_gyakornok_idegen_kulcs" refer="etterem_kulcs">
            <xs:selector xpath="Gyakornok"/>
            <xs:field xpath="@E_GY"/>
        </xs:keyref>

        <xs:unique name="unique_foszakacs">
            <xs:selector xpath="Foszakacs"/>
            <xs:field xpath="@E_F"/>
        </xs:unique>

    </xs:element>


    <xs:complexType name="etteremTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Cim" type="cimTipus"/>
        </xs:sequence>
        <xs:attribute name="EKod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="cimTipus">
        <xs:sequence>
            <xs:element name="Varos" type="xs:string"/>
            <xs:element name="Utca" type="xs:string"/>
            <xs:element name="Hazszam" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="foszakacsTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Eletkor" type="xs:integer"/>
            <xs:element name="Vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="FKod" type="xs:string" use="required"/>
        <xs:attribute name="E_F" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="szakacsTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Reszleg" type="xs:string"/>
            <xs:element name="Vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="SzKod" type="xs:string" use="required"/>
        <xs:attribute name="E_SZ" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="gyakorlatTipus">
        <xs:sequence>
            <xs:element name="Kezdete" type="xs:string"/>
            <xs:element name="Idtartama" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="gyakornokTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Gyakorlat" type="gyakorlatTipus"/>
            <xs:element name="Muszak" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="GyKod" type="xs:string" use="required"/>
        <xs:attribute name="E_GY" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="vendegTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Eletkor" type="xs:integer"/>
            <xs:element name="Cim" type="cimTipus"/>
        </xs:sequence>
        <xs:attribute name="VKod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="rendelesTipus">
        <xs:sequence>
            <xs:element name="osszeg" type="xs:integer"/>
            <xs:element name="etel" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="e_v_e" type="xs:string" use="required"/>
        <xs:attribute name="e_v_v" type="xs:string" use="required"/>
    </xs:complexType>

    

</xs:schema>

=== akos-asztalos443/JTUBQHWebXML/JTUBQH_1014/JTUBQH_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<JTUBQH_Vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="JTUBQH_XMLSchema.xsd">

    <Etterem EKod="e1">
        <Nev>Trófea</Nev>
        <Cim>
            <Varos>Budapest</Varos>
            <Utca>Visegrádi</Utca>
            <Hazszam>13</Hazszam>
        </Cim>
    </Etterem>

    <Etterem EKod="e2">
        <Nev>Gundel</Nev>
        <Cim>
            <Varos>Budapest</Varos>
            <Utca>Gundel Károly</Utca>
            <Hazszam>4</Hazszam>
        </Cim>
    </Etterem>

    <Foszakacs FKod="f1" E_F="e1">
        <Nev>Havas Péter</Nev>
        <Eletkor>35</Eletkor>
        <Vegzettseg>Szakközépiskola</Vegzettseg>
        <Vegzettseg>Institut Paul Bocuse</Vegzettseg> 
    </Foszakacs>

    <Foszakacs FKod="f2" E_F="e2">
        <Nev>Nagy Károly</Nev>
        <Eletkor>30</Eletkor>
        <Vegzettseg>Szakközépiskola</Vegzettseg>
        <Vegzettseg>La Cordon Bleu</Vegzettseg> 
    </Foszakacs>

    <Szakacs SzKod="sz1" E_SZ="e1">
        <Nev>Nagy István</Nev>
        <Reszleg>Saucier</Reszleg>
        <Vegzettseg>Technikus</Vegzettseg>
        <Vegzettseg>La Cordon Bleu</Vegzettseg>
        <Vegzettseg>Institut Paul Bocuse</Vegzettseg>
    </Szakacs>

    <Szakacs SzKod="sz2" E_SZ="e2">
        <Nev>Nagy Péter</Nev>
        <Reszleg>Entremetier</Reszleg>
        <Vegzettseg>Szakközépiskola</Vegzettseg>
        <Vegzettseg>La Cordon Bleu</Vegzettseg>
    </Szakacs>

    <Szakacs SzKod="sz3" E_SZ="e2">
        <Nev>Szabó Dávid</Nev>
        <Reszleg>Gardemanger</Reszleg>
        <Vegzettseg>Szakközépiskola</Vegzettseg>
    </Szakacs>

    <Szakacs SzKod="sz4" E_SZ="e1">
        <Nev>Szabó Dávid</Nev>
        <Reszleg>Gardemanger</Reszleg>
        <Vegzettseg>Szakközépiskola</Vegzettseg>
        <Vegzettseg>La Cordon Bleu</Vegzettseg>
    </Szakacs>

    <Gyakornok GyKod="gy1" E_GY="e1">
        <Nev>Bordás Dávid</Nev>
        <Gyakorlat>
            <Kezdete>2023.08.20</Kezdete>
            <Idtartama>2 hónap</Idtartama>
        </Gyakorlat>
        <Muszak>Délelőtt</Muszak>
        <Muszak>Este</Muszak>
    </Gyakornok>

    <Gyakornok GyKod="gy2" E_GY="e2">
        <Nev>Szilágyi István</Nev>
        <Gyakorlat>
            <Kezdete>2023.06.01</Kezdete>
            <Idtartama>4 hónap</Idtartama>
        </Gyakorlat>
        <Muszak>Délután</Muszak>
    </Gyakornok>

    <Gyakornok GyKod="gy3" E_GY="e1">
        <Nev>Szentpétery Ferenc</Nev>
        <Gyakorlat>
            <Kezdete>2023.01.01</Kezdete>
            <Idtartama>10 hónap</Idtartama>
        </Gyakorlat>
        <Muszak>Délelőtt</Muszak>
        <Muszak>Délután</Muszak>
    </Gyakornok>

    <Vendeg VKod="v1">
        <Nev>Fekete Péter</Nev>
        <Eletkor>21</Eletkor>
        <Cim>
            <Varos>Miskolc</Varos>
            <Utca>Dobó</Utca>
            <Hazszam>12</Hazszam>
        </Cim>
    </Vendeg>

    <Vendeg VKod="v2">
        <Nev>Bordás Áron</Nev>
        <Eletkor>25</Eletkor>
        <Cim>
            <Varos>Eger</Varos>
            <Utca>Dobó</Utca>
            <Hazszam>12</Hazszam>
        </Cim>
    </Vendeg>

    <Vendeg VKod="v3">
        <Nev>Kiss Hajnalka</Nev>
        <Eletkor>26</Eletkor>
        <Cim>
            <Varos>Miskolc</Varos>
            <Utca>Egyetem-város</Utca>
            <Hazszam>1</Hazszam>
        </Cim>
    </Vendeg>

    <rendeles e_v_e="e1" e_v_v="v2">
        <osszeg>6200</osszeg>
        <etel>Túrós csusza pörccel</etel>
    </rendeles>

    <rendeles e_v_e="e2" e_v_v="v2">
        <osszeg>8000</osszeg>
        <etel>Steak</etel>
    </rendeles>

    <rendeles e_v_e="e1" e_v_v="v2">
        <osszeg>12500</osszeg>
        <etel>Gulyásleves és Somlói galuska</etel>
    </rendeles>

    <rendeles e_v_e="e2" e_v_v="v3">
        <osszeg>15400</osszeg>
        <etel>Kacsasült párolt káposztával</etel>
    </rendeles>

</JTUBQH_Vendeglatas>
